# Generated by Django 4.1.3 on 2023-03-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedfiles',
            name='Product_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
