# Generated by Django 4.1.3 on 2023-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_threedfiles_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecords',
            name='o_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='s_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threedfiles',
            name='req_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
