# Generated by Django 4.1.3 on 2023-04-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderrecords_o_id_alter_products_p_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTool',
            fields=[
                ('p_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review_count', models.CharField(default='', max_length=255)),
                ('availability', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'PricingTool',
            },
        ),
    ]
