# Generated by Django 4.1.3 on 2023-04-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_p_threedkinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='p_threedkinks',
            new_name='p_threedlinks',
        ),
    ]
