# Generated by Django 4.1.3 on 2023-04-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_p_threedkinks_products_p_threedlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_threedlinks',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
