# Generated by Django 4.1.3 on 2023-04-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_products_p_threedlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtool',
            name='price',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pricingtool',
            name='rating',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pricingtool',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
