# Generated by Django 4.1.3 on 2023-04-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_pricingtool_price_alter_pricingtool_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtool',
            name='availability',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pricingtool',
            name='review_count',
            field=models.CharField(default='', max_length=500),
        ),
    ]
