# Generated by Django 4.1.3 on 2023-04-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_pricingtool_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrecords',
            old_name='ShippingStatus',
            new_name='Status',
        ),
    ]
