# Generated by Django 4.1.3 on 2023-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_shippingstatus_orderrecords_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('Reviewer_name', models.CharField(default='', max_length=255)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
